### PR TITLE
Added stylesheeting and rendering of grades.csv using tables.

### PR DESCRIPTION
**Pull request by rxg**

### CODE REVIEW

**Comment by winstan** [comment]
@rxg - Thanks for this. I'd like to pass the changes on to @natashamm in concept to refine. Two main things:
1. The CSS should be in a separate file. I think probably a 'default' css file that users can copy and override.
2. The table generator creates a table per csv entry. It should be one table with all entries. I think folding the build_table logic into the showGrades function would work.

**Comment by joelpittet** [comment]
Probably overkill (because it adds composer to the mix) but I thought I'd share because I was trying to do something similar with table building in PHP and stumbled upon this library.

https://github.com/jupitern/table/

@rxg You're table builder is probably more practical for this use-case than the library, but hopefully worth knowing about alternatives if you need something.

**Comment by rxg** [comment]
Thanks y'all!  BTW, the original table-building code that I based this on is probably a better starting point than my adaptation.  I think it basically does what is needed to make multi-row tables.  I was trying to stay close to the current behaviour with my modification so as not to convolute things.  
See [https://stackoverflow.com/a/19294311/9100](https://stackoverflow.com/a/19294311/9100)

**Comment by rxg** [comment]
Procrastination is a super-power:  I updated the implementation to make one table of many rows.  Sorry if I stole someone's work (or you're welcome if I saved someone from work :) ).

**Comment by winstan** [comment]
See https://github.com/ubc-cpsc/handback/pull/4

**Pull request closed without merging**
